# See default at https://github.com/bbatsov/rubocop/blob/master/config/default.yml


# Common configuration.
AllCops:
  Exclude:
    - 'examples/cookbooks/**/*'


# Modified Cops:
Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 50

Metrics/LineLength: # TODO: Lower to 150
  Max: 210

Style/IndentationWidth:
  Width: 2

Style/VariableName:
  EnforcedStyle: snake_case

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines
  Exclude:
    - 'spec/**/*'

Style/GlobalVars:
  AllowedVariables: [
    $server_created  # For Spec testing: (required to allow 2 different responses when searching for a server profile)
  ]


# Disabled Cops:
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/GuardClause: # TODO: Re-enable at some point
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/RescueException:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
